fix = true
include = ["*.py"]
indent-width = 4
line-length = 120
output-format = "json"
respect-gitignore = true
show-fixes = true
target-version = "py312"

[format]
indent-style = "tab"
skip-magic-trailing-comma = true

[lint.flake8-annotations]
allow-star-arg-any = true
suppress-dummy-args = true
suppress-none-returning = true

[lint.flake8-bandit]
hardcoded-tmp-directory = ["/_docx_temp", "/_docx_logs"]

[lint.flake8-comprehensions]
allow-dict-calls-with-keyword-arguments = true

[lint.flake8-implicit-str-concat]
allow-multiline = false

[lint.flake8-tidy-imports]
ban-relative-imports = "all"

[lint.flake8-type-checking]
exempt-modules = ["typing", "typing_extensions"]
runtime-evaluated-decorators = ["docx_modify.interface.is_bool"]

[lint.flake8-unused-arguments]
ignore-variadic-names = true

[lint.isort]
detect-same-package = true
