name: Build Windows EXE

on:
  push:
    branches: [ gui ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install uv
          uv sync --dev
          uv pip install pyinstaller

      - name: Build with PyInstaller (using spec file)
        run: uv run pyinstaller --noconfirm --distpath github_exe/ docx_modify/docx_modify.exe.spec

      # Create a GitHub Release and upload exe to it
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: build-${{ github.run_number }}
          name: "Automated build ${{ github.run_number }}"
          files: github_exe/docx_modify.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
